### PR TITLE
tidy up macro

### PR DESCRIPTION
**Pull request by 0jdxt**
this should be all :)

### CODE REVIEW

**Comment by zwpaper** [comment]
@0jdxt I merged this not blocking the PR upstream, but I was curious about how do you choose between macro and function, could you give me some advice or opinion?

**Comment by 0jdxt** [comment]
Hey man, I would say in general a function is better, but macros have a specific use case - reducing repetitive code.
So for example, if you wanted to create structs for each planet:
```rust
struct Mercury {
	mass: 0.055,
	period: 0.24,
}

struct Earth {
	mass: 1.0,
	period: 1.0,
}

...
```
If you wanted to reduce repitition, you could't use a function to produce these so you would have a macro:
```rust
macro_rules! planet {
	($name:ident, $mass:expr, $period:expr) => {
		struct $name {
			mass: $mass,
			period: $period,
		}
	}
}

planet!(Mercury, 0.055, 0.24);
planet!(Earth, 1.0, 1.0);
```
So macros are ideal for code that can't be put into a function but is repetitive and since macros have variable parameters, you can tidy up repetitive but slightly different code very nicely! That's why I initially did a macro:

```rust
macro_rules! bad_utf8 {
    ($tmp:expr, $e:expr) => {{
        let mut fname = format!($e, $tmp.path().to_str().unwrap())
            .as_bytes()
            .to_vec();
        fname.push(0xa7);
        fname.push(0xfd);
        fname
    }};
    ($tmp:expr, $e:expr, $v:expr) => {{
        let mut fname = bad_utf8!($tmp, $e);
        fname.append($v.as_bytes().to_vec().as_mut());
        fname
    }};
}
```

In this case I initially didn't see how to turn it into a function since the code for each bit was slightly different but I played with it and figured out how to have it as a function, rather than a recursive macro.

**Comment by zwpaper** [comment]
@0jdxt got it, thank you so much for the explanation

**Comment by 0jdxt** [comment]
no problem :) also after you asked, I did some benchmarking which I should've done in the first place and found that the macro and function run in the same time so didn't matter in this case but benchmarking is an easy way to test if a function/macro version is significantly faster than the other.

**Pull request merged**
